### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by crazycatlass95** [TheBarret/Delta#1]
[Failure] Could not find file 'C:\Users\cat\Desktop\Delta-master\Delta.Library\stdio.vb'.
[Failure] Could not find file 'C:\Users\cat\Desktop\Delta-master\Delta.Library\Exceptions.vb'.
[Failure] Could not find file 'C:\Users\cat\Desktop\Delta-master\Delta.Core\Syntax\IfElse.vb'.
[Failure] Could not find file 'C:\Users\cat\Desktop\Delta-master\Delta.Core\Syntax\Sub.vb'.
[Failure] Could not find file 'C:\Users\cat\Desktop\Delta-master\Delta.Core\Syntax\Loop.vb'.

**Comment by TheBarret** [comment]
Forgot to add  the files in the github, sorry!

**Comment by crazycatlass95** [comment]
Thank you.
nice project
