### ISSUE TITLE
small changes

### ISSUE THREAD

**Issue by crazycatlass95** [TheBarret/Delta#2]
github releases
------
upload stable code to releases so we can test :)
https://github.com/TheBarret/Delta/releases

Redundant Code
-------

https://msdn.microsoft.com/en-us/library/8bf5hy2e(v=vs.110).aspx
If the file name that is passed to the path parameter already exists at the specified directory, the file will be overwritten without notice.

https://github.com/TheBarret/Delta/blob/master/Delta.IDE/Helpers.vb#L50-L59

Tmp could not be loaded
-------

C:\Users\crazy\Desktop\Tmp\Tmp.vbproj : error  : The project file could not be loaded.

less code
-------
change

        If (message.IsError) Then
                    item.ForeColor = Color.Red
                    item.SubItems.Add(message.Message)
                Else
                    item.ForeColor = Color.Blue
                    item.SubItems.Add(message.Message)
                End If

to

        If (message.IsError) Then
                    item.ForeColor = Color.Red
                Else
                    item.ForeColor = Color.Blue
               end if
        item.SubItems.Add(message.Message)

**Comment by TheBarret** [comment]
I totally missed that, thanks for keeping me on track. For the 'tmp' project thats a controlled sub-application that helps me compare my emitted opcode to a VS compiled version.

**Comment by crazycatlass95** [comment]
thank you
